steps:
  build_svc:
    image: quay.io/podman/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_NAME: anros/crm-back-svc
      IMAGE_TAG: latest
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    commands:
      - podman login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      - podman pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG || true
      - podman build -f docker/svc/Dockerfile --cache-from $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
      - podman push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  build_nginx:
    image: quay.io/podman/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_NAME: anros/crm-back-nginx
      IMAGE_TAG: latest
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    commands:
      - podman login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      - podman pull $REGISTRY/$IMAGE_NAME:$IMAGE_TAG || true
      - podman build -f docker/nginx/Dockerfile --cache-from $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
      - podman push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

